# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c408f45e335761743e0b9759aa6aa9fd74ebf004ccb394ebf127ac1ae479af71dad6342db57ddeda5b616cd4c02bf4f14d968fec770ba637e68fa7dcad7b6df

test:
  secret_key_base: edf637799aebfbc2eb912611ab6a602ba33c706fb0c9d43d02a639f8fb1b20fb092a4de6f0c7531fedbaf7ff7aa7bdc7117b995a3592c1c58af80500804d338a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
